n1 = input("how many slices of pizza did you have at the start ")
n2 = input("and how many have you eaten ")
n1 = int(n1)
n2 = int(n2)
n3 = (n1-n2)
print("you have this many pizza slices left ", n3)
